### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by federman** [randy3k/SendREPL#2] opened 2016-07-19 15:27 UTC
Here are the error messages I receive when starting st3

reloading plugin Pywin32.setup
Pywin32: Added 'win32'
Pywin32: Added 'win32/lib'
Pywin32: Added 'win32com'
Pywin32: Added 'win32comext'
reloading plugin SendREPL.choose_repl
reloading plugin SendREPL.clipboard
Traceback (most recent call last):
  File "E:\portableapps\st\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "E:\portableapps\st\Data\Packages\SendREPL\clipboard.py", line 7, in <module>
    import win32clipboard
ImportError: DLL load failed: The specified module could not be found.
reloading plugin SendREPL.send_repl
Traceback (most recent call last):
  File "E:\portableapps\st\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "E:\portableapps\st\Data\Packages\SendREPL\send_repl.py", line 4, in <module>
    from .text_sender import TextSender
  File "E:\portableapps\st\Data\Packages\SendREPL\text_sender.py", line 6, in <module>
    from .r import send_to_r
  File "E:\portableapps\st\Data\Packages\SendREPL\r\__init__.py", line 3, in <module>
    from ..clipboard import clipboard
  File "E:\portableapps\st\Data\Packages\SendREPL\clipboard.py", line 7, in <module>
    import win32clipboard
ImportError: DLL load failed: The specified module could not be found.
reloading plugin SendREPL.settings
reloading plugin SendREPL.text_getter
reloading plugin SendREPL.text_sender
Traceback (most recent call last):
  File "E:\portableapps\st\sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "E:\portableapps\st\Data\Packages\SendREPL\text_sender.py", line 6, in <module>
    from .r import send_to_r
  File "E:\portableapps\st\Data\Packages\SendREPL\r\__init__.py", line 3, in <module>
    from ..clipboard import clipboard
  File "E:\portableapps\st\Data\Packages\SendREPL\clipboard.py", line 7, in <module>
    import win32clipboard
ImportError: DLL load failed: The specified module could not be found.

**Comment by randy3k** [comment] 2016-07-19 15:33
Did you install `Pywin32` manually?  [Pywin32](https://github.com/SublimeText/Pywin32) is a Sublime Text package where SendREPL depends on a Package Control dependency [python-pywin32](https://github.com/randy3k/sublime-pywin32).

The dependency should be installed automatically when SendREPL is installed, though it may take a while.

**Comment by randy3k** [comment] 2016-07-19 15:46
I guess I undersatnd what's happening. It seems that 32bit binary of python-pywin32 is not working.

**Comment by federman** [comment] 2016-07-19 15:48
I let st3 install it

Get Outlook for iOS




On Tue, Jul 19, 2016 at 11:33 AM -0400, "Randy Lai" <notifications@github.com> wrote:












Did you install Pywin32 manually?  Pywin32 is a Sublime Text package where SendREPL depends on a Package Control dependency python-pywin32.



The dependency should be installed automatically when SendREPL is installed, though it may take a while.

**Comment by randy3k** [comment] 2016-07-19 16:10
I guess it was caused by an incompleted installation. Please remove SendREPL and python-pywin32 under your Sublime Text package folder and reinstall SendREPL from Package Control again.

**Comment by federman** [comment] 2016-07-20 13:11
I did without success.  Tried a different computer with same results

Get Outlook for iOS




On Tue, Jul 19, 2016 at 12:10 PM -0400, "Randy Lai" <notifications@github.com> wrote:












I guess it was caused by an incompleted installation. Please remove SendREPL and python-pywin32 under your Sublime Text package folder and reinstall SendREPL from Package Control again.

**Comment by randy3k** [comment] 2016-07-20 13:31
By the way, is your sublime text 32 or 64 bit?

**Comment by federman** [comment] 2016-07-20 13:43
One is 32 bit and one is 64 bit 

    On Wednesday, July 20, 2016 9:31 AM, Randy Lai <notifications@github.com> wrote:
 
 

 By the way, is your sublime text 32 or 64 bit?—

**Comment by randy3k** [comment] 2016-07-20 14:06
It is likely caused by [this](http://stackoverflow.com/questions/22490233/win32com-import-error-python-3-4), will fix soon.

**Comment by randy3k** [comment] 2016-07-20 14:52
Should be fixed by now. You may need to reinstall SendREPL again. The update will be available via Package Control very soon.

**Closed by randy3k** 2016-07-20 14:52 UTC

**Comment by randy3k** [comment] 2016-07-20 14:55
Please reopen it if the update does fix the issue.

**Comment by randy3k** [comment] 2016-07-20 17:00
Just a side note: to reinstall the dependency, you will need to remove the folder `python-pywin32` under `Sublime Text 3/Pacakges` and run the command `Package Control: Satisfy Dependencies`.

**Comment by federman** [comment] 2016-07-20 17:07
Thanks






On Wed, Jul 20, 2016 at 1:00 PM -0400, "Randy Lai" <notifications@github.com> wrote:












Just a side note: to reinstall the dependency, you will need to remove the folder python-pywin32 under Sublime Text 3/Pacakges and run the command Package Control: Satisfy Dependencies.

**Comment by kevin-stuart** [comment] 2016-12-02 12:17
I had this issue again; no matter what I did, I always got "ImportError: DLL load failed". I removed pywin32 and SendREPL mutliple times and reinstalled with satisfy dependencies. I updated to the latest version of ST3 (3126) by using the built-in update feature. Nothing worked.

A working solution I came up with was to copy the pywintypes33.dll to the root of my SublimeText installation, i.e. copying `SublimeText3x64\Data\Packages\python-pywin32\st3_windows_x64\pywin32_system32\pywintypes33.dll` to `SublimeText3x64\pywintypes33.dll`. How is this supposed to work, is this supposed to be done by SendREPL during install or why is the DLL not found?

**Comment by randy3k** [comment] 2016-12-02 15:55
It is strange. The path should be set correctly by Package Control [loader][1] code.
Could you check run the following in Sublime console and check if the path to `pywin32_system32` is there?

```
from os import environ; environ["PATH"]
```

[1]: https://github.com/randy3k/sublime-pywin32/blob/master/loader.code#L22

**Comment by kevin-stuart** [comment] 2016-12-02 16:19
Oh I see the problem: the items in PATH are mostly separated correctly with ";", but the final item is not, it is the following:

`C:\\programs\\SUBLIM~3\\Data\\Packages\\python-pywin32\\st3_windows_x64\\pywin32_system32:/usr/local/bin:/usr/local/bin`

So the final item is using ":" instead of ";" and adding /usr/local/bin to the pywin32_system32, thereby making it one single item for Windows, and therefore pywin32_system32 is not part of the path. How is PATH constructed in ST3? Is it done by SendREPL or is this some problem with my system? I have Cygwin installed as well. Is this the problem?

**Comment by randy3k** [comment] 2016-12-02 17:03
The `PATH` variable is updated by Package Control via the [loaded code][1] for `python-pywin32`. It should only add the path to `pywin32_system32` to the PATH variable.

My suspicion is that you have installed a not-well-designed Sublime Text package which has added `:/usr/local/bin:/usr/local/bin` to the PATH variable. FYI, the PATH variable is delimited by colons on Linux and macOS.

 [1]: https://github.com/randy3k/sublime-pywin32/blob/master/loader.code#L22

**Comment by kevin-stuart** [comment] 2016-12-04 09:36
Do you have any suggestion how I can find out which extension is doing this? It also looks like it is done two times. How is the order determined? If pywin32 would have been appended earlier, this would not have been a problem, but something else would have "broken".

**Comment by kevin-stuart** [comment] 2016-12-05 12:51
I tried uninstalling plugins and restarting ST3 by using a copy of my installation and now believe that this plugin is at fault: https://github.com/munro/SublimeGraphvizPreview

However, I have not yet figured out what it is doing wrong. I'll try reporting it.
